version: '3.9'
services: 
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8001:8000
        depends_on: 
            - db

    queue:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        depends_on: 
            - db        

    db:
        platform: linux/x86_64
        image: mysql:8.0
        environment: 
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            #MYSQL_DATABASE: Gestion_Optic
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            #MYSQL_ROOT: root
            MYSQL_ALLOW_EMPTY_PASSWORD : 'yes'
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 3306:3306